import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";
import heavyrain from '../Images/heavy-rain.jpg'
import { useRouter } from 'next/router'


export default function Home() {
  let router= useRouter()
  
  function redirect() {
    router.push('/about') 
  }
  
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />

      </Head>

      <main className={styles.main}>
      <Image
          width={724}
          height={324}
          objectFit="cover"
          src={heavyrain}
          alt="vercel logo "
        />
        <button onClick={redirect}> Redirect</button>
        <h1 className={styles.title}>
          Welcome to Next.js ! src/folder {process.env.envirement} 
        </h1>
        <Link href="/page">
          <a>about</a>
        </Link>

        <Link href="/protected">
          <a>protected</a>
        </Link>
      </main>

    </div>
  )
}
